#!/usr/bin/env python3

from imp import load_source
import traceback
import sys

algorithm = load_source('algorithm', './algorithm').algorithm

def main():
    try: # if anything breaks exit 84
        main = algorithm() # parces, inits the class and computes the program
        print(main) # prints the result
    except Exception as e:
        print(e, file=sys.stderr, end="") # print the error
        traceback.print_exc() # where it broke # prints the debug info
        exit (84)
    return 0
if __name__ == "__main__":
    main()