#!/usr/bin/env python3

import sys

class parser:
    def __init__(this, parce:bool = False):
        this.parsed_data:list = []
        this.list_index:list = []
        this.parse_data:list = []
        this.years:list = []
        this.countries:list = []

        if (parce):
            this.parse()

    def __print_help(this) -> None:
        print("USAGE")
        print("\t./207demography code\n")
        print("DESCRIPTION")
        print("\tcode\tcountry code")

    def parse(this) -> None:
        if (len(sys.argv) >= 2):
            if (sys.argv[1] == "-h"):
                this.__print_help()
                exit(0)
            else:
                this.__load_file()
                this.__parse_args()
                this.__parse_data()
        else:
            this.__print_help()
            raise Exception("Invalid number of arguments")

    def __load_file(this) -> None:
        try:
            file = open("207demography_data.csv")
            lines = file.readlines()
            file.close()
            this.__parce_data(lines)
        except:
            raise Exception("Data File not found")

    def __parce_data(this, lines:list) -> None:
        for line in lines:
            this.parsed_data.append(line.split(';'))

    def __parse_args(this) -> None:
        for i in range(1, len(sys.argv)):
            this.list_index.append(this.__get_index(sys.argv[i]))

    def __parse_data(this) -> None:
        data_obj:list = this.parsed_data
        list_index:list = this.list_index
        parse_data = []
        new_list = []
        this.parse_data = []
        this.countries = []
        this.years = []

        for i in list_index:
            parse_data.append(data_obj[i])
        this.years = data_obj[0][2:]
        this.years[-1] = this.years[-1][:-1]
        this.years = [int(i) for i in this.years]
        for country_data in parse_data:
            this.countries.append(country_data[0])
            del country_data[0:2]
            country_data[-1] = country_data[-1][:-1]
            this.parse_data.append([int(i) for i in country_data])
        this.parse_data
        new_list = [ 0 for _ in range(len(this.parse_data[0]))]
        for i in range(len(this.parse_data)):
            for j in range(len(this.parse_data[i])):
                new_list[j] = (this.parse_data[i][j] + new_list[j])
        this.parse_data = new_list

    def __get_index(this, country:str) -> int:
        for i in range(len(this.parsed_data)):
            if (this.parsed_data[i][1] == country):
                return i
        raise Exception("Country not found:" + country)

    def get_parced_data(this) -> list:
        return [this.countries, this.years, this.parse_data]

