#!/usr/bin/env python3

from imp import load_source
import traceback
import sys

algorithm = load_source('algorithm', './algorithm').algorithm

def main():
    try: # if anything breaks exit 84
        main = algorithm() # parces and inits the class
        print(main, end="") # computes the program and prints the results
    except Exception as e:
        print(e, file=sys.stderr) # print the error
        traceback.print_exc() # where it broke # prints the debug info
        exit (84)
    return 0
if __name__ == "__main__":
    main()