#!/usr/bin/env python3

import sys

class parser:
    def __init__(this, parce:bool = False):
        this.a:float = 0
        if (parce):
            this.parse()

    def parse(this) -> None:
        if (len(sys.argv) == 2):
            if (sys.argv[1] == "-h"):
                this.__print_help()
                exit(0)
            this.a = float(sys.argv[1])
            if (this.a < 0 or this.a > 2.5):
                raise Exception("Invalid args must be between 0 and 2.5")
        else:
            raise Exception("Invalid number of args")

    def __print_help(this) -> None:
        print("USAGE")
        print("\t./204ducks a")
        print("DESCRIPTION")
        print("\ta constant between 0 and 2.5")

    def get_parced_data(this) -> float:
        return this.a

