#!/usr/bin/env python3

from math import floor, sqrt, exp

class utils:
    def GetAverageTime(a:float) -> list:
        time = []
        res:float = (3 * (a + 2)) / 8
        floored = floor(res)
        sec = (res - floored) * 60
        time.append(floored)
        time.append(round(sec, 1))
        return time

    def GetAverage(a:float) -> float:
        return (3 * (a + 2)) / 8

    def GetVariance(a:float) -> float:
        return sqrt((7 / 16) * (3 * a + 2) - (utils.GetAverage(a) * utils.GetAverage(a)))

    def GetCalcPrim(a:float, t:float) -> float:
        return (1/2) * exp(-4 * t) * (exp(t) - 1)**2 * (2 * (exp(t) + 1)**2 - a * (2 * exp(t) + 1))

    def ParceTime(t:float) -> list:
        m = int(t / 60)
        s = t - (m * 60)
        return [m, s]