#!/usr/bin/env python3

import sys

class parser:
    def __init__(this, parce:bool = False):
        this.u:int = 0
        this.s:int = 0
        this.iq1:int = 0
        this.iq2:int = 0
        if (parce):
            this.parse()

    def parse(this) -> None:
        if (len(sys.argv) == 2):
            if (sys.argv[1] == "-h"):
                this.__print_help()
                exit(0)
        if (len(sys.argv) < 3 or len(sys.argv) > 5):
            raise Exception("Invalid arguments")
        this.u = int(sys.argv[1])
        this.s = int(sys.argv[2])
        this.iq1 = 0
        this.iq2 = 201
        this.mode = 0
        if (len(sys.argv) >= 4):
            this.iq1 = int(sys.argv[3])
            this.mode = 1
        if (len(sys.argv) == 5):
            this.iq2 = int(sys.argv[4])
            this.mode = 2
        if (this.u < 0 or this.s < 0 or this.iq1 < 0 or this.iq2 < 0 or this.iq2 > 201 or this.u > 200):
            raise Exception("Negative arguments")
        if (this.iq1 > 200 or this.iq1 > this.iq2):
            raise Exception("IQ1 > IQ2")

    def __print_help(this) -> None:
        print("USAGE")
        print("\t./205IQ u s [IQ1] [IQ2]")
        print("DESCRIPTION")
        print("\tu\tmean")
        print("\ts\tstandard deviation")
        print("\tIQ1\tminimum IQ")
        print("\tIQ2\tmaximum IQ")

    def get_parced_data(this) -> list:
        return [this.u, this.s, this.iq1, this.iq2, this.mode]

