#!/usr/bin/env python3

import sys

class parser:
    def __init__(this, parce:bool = False):
        this.n:int = 0
        this.a:int = 0
        this.h:int = 0
        this.sd:int = 0
        if (parce):
            this.parse()

    def parse(this) -> None:
        if (len(sys.argv) == 2):
            if (sys.argv[1] == "-h"):
                this.__print_help()
                exit(0)
        if (len(sys.argv) != 5):
            raise Exception("Invalid arguments")
        this.n = int(sys.argv[1])
        this.a = int(sys.argv[2])
        this.h = int(sys.argv[3])
        this.sd = int(sys.argv[4])
        if (this.n < 0 or this.a < 0 or this.h < 0 or this.sd < 0):
            raise Exception("Negative arguments")

    def __print_help(this) -> None:
        print("USAGE")
        print("\t./206neutrinos n a h sd\n")
        print("DESCRIPTION")
        print("\tn number of values")
        print("\ta arithmetic mean")
        print("\th harmonic mean")
        print("\tsd standard deviation")

    def get_parced_data(this) -> list:
        return [this.n, this.a, this.h, this.sd]

