#!/usr/bin/env python3

import math

class utils:
    def permutations(n):
        return math.factorial(n)

    def combinations(n: int, k: int) -> int:
        return math.comb(n, k)

    def get_apparition(dice: list, nb:int):
        count = 0
        for i in dice:
            if i == nb:
                count += 1
        return count

    def get_binomial(n, k):
        return (math.comb(n, k) * math.pow(1 / 6, k) * math.pow(5 / 6, n - k))