#!/usr/bin/env python3

from math import sqrt

class utils:
    def get_interval(x:float, i:float) -> list:
        return [100 * min(max(x - i, 0), 1), 100 * min(max(x + i, 0), 1)]

    def get_variance(pSize:int, sSize:int, p:float) -> float:
        return ((p * (1 - p)) / sSize) * ((pSize - sSize) / (pSize - 1))

    def get_CI95(p:float, v:float) -> list:
        return utils.get_interval(p, 1.96 * sqrt(v))

    def get_CI99(p:float, v:float) -> list:
        return utils.get_interval(p, 2.58 * sqrt(v))